# Generated by Django 5.1.3 on 2024-11-12 04:03

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_Chat', '0002_groupmessages_file_alter_groupname_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessages',
            name='file',
        ),
        migrations.AddField(
            model_name='groupmessages',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='groupname',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
    ]
