# Generated by Django 5.1.3 on 2024-11-12 04:24

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_Chat', '0003_remove_groupmessages_file_groupmessages_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessages',
            old_name='files',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='groupname',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
    ]
